import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebars:
 * - Scans the `docs/` folder and builds a sidebar that mirrors your folder structure.
 * - Any `README.md` or `index.md` inside a folder becomes that folder's introduction.
 * - Version subfolders like `docs/fast2/v1` are grouped automatically under their product.
 */
const sidebars: SidebarsConfig = {
  // One global sidebar that includes every document under `docs/`
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
