// sidebars.ts – autogénéré "par produit"
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    { type: 'doc', id: 'intro', label: 'Introduction', key: 'intro' },
    { type: 'autogenerated', dirName: 'fast2' },
    { type: 'autogenerated', dirName: 'arender' },
    { type: 'autogenerated', dirName: 'flowerdocs' },
    // ajoute d'autres répertoires si besoin
  ],
};

export default sidebars;
