title = "FlowerDocs"
theme = "hugo-universal-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Enable emoji
enableEmoji = true

uglyurls = false
relativeURLs = false
canonifyURLs = false

pygmentsCodefences = true
pygmentsStyle = "monokailight"

# Define the number of posts per page
paginate = 10

enableRobotsTXT=true

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
[languages]
  [languages.fr]
  	languageCode = "fr"
    contentDir = 'content/french'
    languageName = 'Français'
	[languages.fr.menu]
		[[languages.fr.menu.main]]
		    name = "FlowerDocs Academy"
		    parent = "resources"
		    url  = "/documentation/learn/"
		    pre = "fas fa-graduation-cap"
		    post = "Découvrez FlowerDocs à travers des modules de formation."
		    weight = 2
		[[languages.fr.menu.main]]
		    name = "Ressources"
		    identifier = "resources"
		    url  = "/documentation/"
		    weight = 7
		[[languages.fr.menu.main]]
		    name = "Actualités"
		    url  = "/blog/"
		    pre = "fas fa-rss"
		    post = "Les actualités du produit et solutions."
		    weight = 8
		[[languages.fr.menu.main]]
		    name = "Documentation"
		    parent = "resources"
		    url  = "/documentation/"
		    pre = "fas fa-book"
		    post = "Toute la documentation en ligne du produit."
		    weight = 1
		[[languages.fr.menu.main]]
		    name = "Releases"
		    parent = "resources"
		    url  = "/releases/"
		    pre = "fas fa-tags"
		    post = "Accéder aux releases du produit"
		    weight = 4
		[[languages.fr.menu.main]]
		    name = "Langues"
		    identifier = "langues"
		    url  = "/documentation/"
		    weight = 1
		[[languages.fr.menu.main]]
		    name = "Français"
		    url  = "/documentation/"
		    parent = "langues"
		    weight = 1
		[[languages.fr.menu.main]]
		    name = "Anglais"
		    url  = "/en/documentation/"
		    parent = "langues"
		    weight = 2
		[[languages.fr.menu.main]]
		    name = "Versions"
		    identifier = "versions"
		    url  = "/documentation/"
		    weight = 2
		[[languages.fr.menu.main]]
		    name = "Actuelle"
		    url  = "https://documentation.flowerdocs.com/documentation/"
		    parent = "versions"
		    weight = 1
		[[languages.fr.menu.main]]
		    name = "2.8 LTS"
		    url  = "https://documentation.flowerdocs.com/lts/documentation/"
		    parent = "versions"
		    weight = 2
    [languages.fr.params]
    	publish="Publiée le"
    	update=", Mise à jour le"
    	lastVersionIs="La dernière version corrective est la"
    	prerequisiteList="Cette version nécessite comme pré-requis les versions des applicatifs suivants :"
    	all="Tous"
    	discover="Découvrir"
    	releasePath="/releases/"
  [languages.en]
  	languageCode = "en"
    contentDir = 'content/english'
    languageName = 'English'
	[languages.en.menu]
		[[languages.en.menu.main]]
		    name = "FlowerDocs Academy"
		    parent = "resources"
		    url  = "/en/documentation/learn/"
		    pre = "fas fa-graduation-cap"
		    post = "Discover FlowerDocs through training modules."
		    weight = 2
		[[languages.en.menu.main]]
		    name = "Ressources"
		    identifier = "resources"
		    url  = "/en/documentation/"
		    weight = 7
		[[languages.en.menu.main]]
		    name = "News"
		    url  = "/en/blog/"
		    pre = "fas fa-rss"
		    post = "Product and solutions news."
		    weight = 8
		[[languages.en.menu.main]]
		    name = "Documentation"
		    parent = "resources"
		    url  = "/en/documentation/"
		    pre = "fas fa-book"
		    post = "All the product online documentation."
		    weight = 1
		[[languages.en.menu.main]]
		    name = "Releases"
		    parent = "resources"
		    url  = "/en/releases/"
		    pre = "fas fa-tags"
		    post = "Access to product releases"
		    weight = 4
		[[languages.en.menu.main]]
		    name = "Languages"
		    identifier = "langues"
		    url  = "/en/documentation/"
		    weight = 1
		[[languages.en.menu.main]]
		    name = "French"
		    url  = "/documentation/"
		    parent = "langues"
		    weight = 2
		[[languages.en.menu.main]]
		    name = "English"
		    url  = "/en/documentation/"
		    parent = "langues"
		    weight = 1
		[[languages.en.menu.main]]
		    name = "Versions"
		    identifier = "versions"
		    url  = "/documentation/"
		    weight = 2
		[[languages.en.menu.main]]
		    name = "Current"
		    url  = "https://documentation.flowerdocs.com/en/documentation/"
		    parent = "versions"
		    weight = 1
		[[languages.en.menu.main]]
		    name = "2.8 LTS"
		    url  = "https://documentation.flowerdocs.com/lts/en/documentation/"
		    parent = "versions"
		    weight = 2
	[languages.en.params]
    	publish="Published on"
    	update=", Updated on"
    	lastVersionIs="The latest patch version is"
    	prerequisiteList="This version requires the following software versions as prerequisites :"
    	all="All"
    	discover="Discover"
    	releasePath="/en/releases/"
[params]
	openSearchMajorVersion = "1.3"
    openSearchMinorVersion = "19"
    companionVersion = "2025.0"

	currentVersion = "2025.2.0"
    arenderCurrentVersion="2023.12.0"
    springBootVersion = "2.7.18"
	fontAwesomeVersion = "6.5.2"
    
	viewMorePostLink = "/blog/"
    author = "Arondor"
    defaultDescription = "FlowerDocs est un outil de communication graphique qui permet de répondre facilement aux besoins métier axés sur la communication entre différents acteurs."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    # purple theme is the same as FlowerDocs application theme
    # style = "purple"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "flowerdocs-support@arondor.com"

    about_us = "ESN créée en 2002 par des spécialistes de la gestion documentaire, propose une gamme de services et de solutions répondant à l’ensemble des besoins dans le domaine."
    copyright = "© Tous droits reservés."

    # Format dates with Go's time formatting
    date_format = "02/01/2006"

    logo = "images/logo.png"
    address = """<p><strong>ARONDOR</strong>
        <br>Siège, 24/26 rue de la Pépinière – 75008 Paris
        <br>Centre de Services, 125 rue du Faubourg Bannier – 45000 Orléans 
        <br>Agence, 47 cours le Rouzic – 33100 Bordeaux
        <br>
        <br>+33 1 71 18 21 00 
        <br>flowerdocs-support@arondor.com
      </p>
      """
    latitude = "48.8752438"
    longitude = "2.3215865"

[Permalinks]
    #documentation = "/:sections/:slug"
	blog = "/blog/:filename/"
    

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
