#################################################################
########################### Languages ###########################

baseURL = "http://arender-documentation-next.s3-website.eu-west-3.amazonaws.com/"