#################################################################
########################### Languages ###########################

buildDrafts = true
baseURL = "http://localhost/"

[params.source]
display = true

[params.documentationonly]
enabled = false
