# .github/workflows/deploy.yml
name: Deploy Docusaurus to gh-pages

on:
  push:
    branches: [ test ]
  workflow_dispatch:

permissions:
  contents: write   # nécessaire pour pousser sur gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author (for the gh-pages commit)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build & Deploy
        env:
          # ⬇️ requis par "docusaurus deploy"
          GIT_USER: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
