name: Hydrate & Deploy Docs

on:
  push:
    branches: [ master, "fast2/v*" ]
  workflow_dispatch:

# Autorise l’écriture (gh-pages)
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # plus robuste pour git worktrees/fetch

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Si tu as un .nvmrc au repo, décommente la ligne suivante et commente la suivante :
          # node-version-file: '.nvmrc'
          node-version: '20.x'
          cache: 'npm'

      - name: Show versions
        run: |
          node -v
          npm -v
          git --version

      - name: Install dependencies (lockfile)
        run: npm ci

      - name: Hydrate versions from branches
        run: bash scripts/hydrate.sh

      - name: Cleanup hydrated markdown for MDX
        run: python3 scripts/ci-cleanup.py

      - name: Generate versions manifest
        run: node scripts/collectVersions.mjs

      - name: Build
        env:
          CI: "true"
          # OPTIONNEL: si besoin de plus de mémoire pour le build
          # NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy