name: deploy-gh-pages

on:
  push:
    branches: [ test ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write       # pour publier sur GitHub Pages
  id-token: write    # requis par actions/deploy-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      # (Optionnel) s'il faut regénérer la navbar/versions après agrégation
      - name: Rebuild versions manifest
        if: ${{ hashFiles('scripts/collectVersions.mjs') != '' }}
        run: node scripts/collectVersions.mjs

      - name: Build site (Docusaurus)
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
