name: Hydrate & Deploy Docs

on:
  push:
    branches: [ master, "fast2/v*", "flowerdocs/v*", "arender/v*" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Important pour récupérer toutes les branches
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Hydrate versions from branches
        run: bash scripts/hydrate.sh

      - name: Generate versions manifest
        run: node scripts/collectVersions.mjs

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
