name: Hydrate & Deploy Docs

on:
  push:
    branches: [ master, "fast2/v*", "flower/v*", "arender/v*" ]
  workflow_dispatch:

# Give the workflow permission to push/deploy (used by the deploy step / gh-pages)
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Important pour récupérer toutes les branches and allow pushing back
          persist-credentials: true
          ref: ${{ github.ref }}
          fetch-tags: true

      - name: Ensure remote branches are available
        run: |
          git fetch --prune --unshallow || true
          git fetch --all --prune
          git fetch origin '+refs/heads/*:refs/remotes/origin/*' || true
          git branch -r

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Hydrate versions from branches
        run: bash scripts/hydrate.sh

      - name: Generate versions manifest
        run: node scripts/collectVersions.mjs

      - name: CI cleanup for MDX
        run: |
          python3 scripts/ci-cleanup.py

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
