name: Deploy Docusaurus to gh-pages

on:
  push:
    branches:
      - test            # Déploie quand la branche test est mise à jour
  workflow_dispatch:     # Permet de le déclencher manuellement

permissions:
  contents: write        # Nécessaire pour pousser sur gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Important pour que docusaurus sache d'où vient le code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and deploy to gh-pages
        env:
          GIT_USER: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"
          npm run deploy
