# .github/workflows/deploy.yml
name: Deploy Docusaurus to gh-pages

on:
  push:
    branches: [ test ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Dossier contenant le site statique généré par Docusaurus
          publish_dir: ./build
          # L'utilisateur qui fera le commit de déploiement
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'