name: Test Hydrate & Build on test

on:
  push:
    branches: [ test ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: refs/heads/test
          fetch-tags: true

      - name: Ensure remote branches are available
        run: |
          git fetch --prune --unshallow || true
          git fetch --all --prune
          git fetch origin '+refs/heads/*:refs/remotes/origin/*' || true
          git branch -r

      - name: Hydrate test from branches
        run: |
          set -e
          HYDRATE_BRANCHES="test/fast2/v1 test/fast2/v2 test/flowerdocs/v1 test/flowerdocs/v2 test/arender/v1 test/arender/v2"
          for b in $HYDRATE_BRANCHES; do
            product=$(echo "$b" | cut -d'/' -f2)
            file_path="docs/${product}/index.md"
            echo "Processing $b -> $file_path"
            # Prefer origin ref if available
            if git show "origin/$b:$file_path" > /dev/null 2>&1; then
              mkdir -p "docs/${product}"
              git show "origin/$b:$file_path" > "docs/${product}/index.md"
              echo "Hydrated $product from origin/$b"
            elif git show "$b:$file_path" > /dev/null 2>&1; then
              mkdir -p "docs/${product}"
              git show "$b:$file_path" > "docs/${product}/index.md"
              echo "Hydrated $product from $b"
            else
              echo "No $file_path in $b"
            fi
          done

      - name: Install Node and build
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps and Build
        run: |
          npm ci
          npm run build

      - name: Test workflow - skip deploy
        run: |
          echo "Test build complete. Deploy step skipped in test workflow."
